import { localDateKey } from "@/lib/sticky/recurrence";
import type { StickyColor, StickyTask, StickyWorkspaceData } from "@/types/sticky";

function iso(now: Date, minutesAgo = 0) {
  return new Date(now.getTime() - minutesAgo * 60_000).toISOString();
}

const MOCKUP_RAIL_LISTS: Array<{ name: string; slug: string; color: StickyColor; active: number }> = [
  { name: "Career", slug: "career", color: "sky", active: 11 },
  { name: "Portfolio", slug: "portfolio", color: "sun", active: 8 },
  { name: "Finance", slug: "finance", color: "mint", active: 2 },
  { name: "Communities + Net...", slug: "communities-net", color: "sky", active: 9 },
  { name: "Internship List", slug: "internship-list", color: "violet", active: 6 },
  { name: "HW Assignments", slug: "hw-assignments", color: "coral", active: 7 },
  { name: "Tests + Quizzes", slug: "tests-quizzes", color: "sun", active: 5 },
  { name: "Projects", slug: "projects", color: "sky", active: 4 },
  { name: "CS", slug: "cs", color: "mint", active: 14 },
  { name: "Business", slug: "business", color: "mint", active: 7 },
  { name: "PA Tasks", slug: "pa-tasks", color: "violet", active: 6 },
  { name: "Skills", slug: "skills", color: "coral", active: 7 },
  { name: "Physical Ability", slug: "physical-ability", color: "mint", active: 8 },
  { name: "Aesthetics", slug: "aesthetics", color: "ink", active: 4 },
  { name: "Diet", slug: "diet", color: "ink", active: 5 },
  { name: "Content Creation", slug: "content-creation", color: "ink", active: 14 },
  { name: "Misc.", slug: "misc", color: "ink", active: 10 },
  { name: "Books", slug: "books", color: "ink", active: 94 },
  { name: "Watch", slug: "watch", color: "ink", active: 80 },
  { name: "Movies/Shows", slug: "movies-shows", color: "ink", active: 10 },
  { name: "Chores", slug: "chores", color: "ink", active: 15 },
];

const MOCKUP_NEXT_TASKS = [
  "https://x.com/1752vc/status/2065476978241605774?s=46",
  "i will never lose sleep again after learning this - alex hormozi",
  "https://www.acquisition.com/hubs/ACQ%20Workshop%20Assets/How%20to%20get%2...",
  "https://www.acquisition.com/hubs/5-Scaling+Frameworks+by-Acquisition.com).pdf?...",
  "thinking/pondering/brainstorming session",
  "https://youtu.be/57IDpTwilWg?si=Ns2FynrFcLGKKPf_",
];

export function createDemoWorkspaceData(): StickyWorkspaceData {
  const now = new Date();
  const todayKey = localDateKey(now);
  const userId = "demo-user";
  const todayId = "demo-list-today";
  const launchId = "demo-list-launch";
  const homeId = "demo-list-home";
  const worklistId = "demo-list-worklist";
  const plateId = "demo-list-plate";
  const inboxTaskId = "demo-task-inbox";
  const polishTaskId = "demo-task-polish";
  const recurringTaskId = "demo-task-recurring";
  const completedTaskId = "demo-task-completed";
  const makeTask = ({
    id,
    listId,
    title,
    details = "",
    color = "sun",
    dueDate = null,
    dueTime = null,
    isCompleted = false,
    sortOrder,
    completedSortOrder = null,
    minutesAgo = 40,
  }: {
    id: string;
    listId: string;
    title: string;
    details?: string;
    color?: StickyColor;
    dueDate?: string | null;
    dueTime?: string | null;
    isCompleted?: boolean;
    sortOrder: number;
    completedSortOrder?: number | null;
    minutesAgo?: number;
  }): StickyTask => ({
    id,
    userId,
    listId,
    title,
    details,
    color,
    dueDate,
    dueTime,
    timezone: "America/Chicago",
    isCompleted,
    completedAt: isCompleted ? iso(now, minutesAgo) : null,
    sortOrder,
    completedSortOrder: isCompleted ? completedSortOrder ?? sortOrder : null,
    createdAt: iso(now, minutesAgo + 90),
    updatedAt: iso(now, minutesAgo),
  });

  return {
    user: {
      id: userId,
      email: "demo@sticky.local",
      displayName: "AR",
      role: "owner",
    },
    lists: [
      {
        id: todayId,
        userId,
        name: "reminders",
        color: "sun",
        sortOrder: 1000,
        createdAt: iso(now, 360),
        updatedAt: iso(now, 8),
      },
      {
        id: launchId,
        userId,
        name: "Next 3",
        color: "sky",
        sortOrder: 2000,
        createdAt: iso(now, 340),
        updatedAt: iso(now, 12),
      },
      {
        id: homeId,
        userId,
        name: "bring",
        color: "mint",
        sortOrder: 3000,
        createdAt: iso(now, 330),
        updatedAt: iso(now, 30),
      },
      {
        id: worklistId,
        userId,
        name: "Current Worklist",
        color: "coral",
        sortOrder: 4000,
        createdAt: iso(now, 320),
        updatedAt: iso(now, 18),
      },
      {
        id: plateId,
        userId,
        name: "Plate",
        color: "violet",
        sortOrder: 5000,
        createdAt: iso(now, 310),
        updatedAt: iso(now, 22),
      },
      ...MOCKUP_RAIL_LISTS.map((list, index) => ({
        id: `demo-list-${list.slug}`,
        userId,
        name: list.name,
        color: list.color,
        sortOrder: 6000 + index * 1000,
        createdAt: iso(now, 300 - index),
        updatedAt: iso(now, 20),
      })),
    ],
    tasks: [
      {
        id: inboxTaskId,
        userId,
        listId: todayId,
        title: "Clear the capture tray",
        details: "Turn loose ideas into real tasks before lunch.",
        color: "sky",
        dueDate: todayKey,
        dueTime: "11:30",
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 1000,
        completedSortOrder: null,
        createdAt: iso(now, 120),
        updatedAt: iso(now, 12),
      },
      {
        id: polishTaskId,
        userId,
        listId: todayId,
        title: "Tighten the details panel",
        details: "Sharper labels, cleaner due controls, and repeat settings that stay out of the way.",
        color: "violet",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 2000,
        completedSortOrder: null,
        createdAt: iso(now, 100),
        updatedAt: iso(now, 20),
      },
      {
        id: recurringTaskId,
        userId,
        listId: todayId,
        title: "Daily planning pass",
        details: "No subtasks on repeating tasks. Keep it fast.",
        color: "sun",
        dueDate: todayKey,
        dueTime: "09:00",
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 3000,
        completedSortOrder: null,
        createdAt: iso(now, 80),
        updatedAt: iso(now, 5),
      },
      {
        id: completedTaskId,
        userId,
        listId: todayId,
        title: "Sketch first pass motion",
        details: "Completion pulse and drag lift are both wired.",
        color: "mint",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: true,
        completedAt: iso(now, 22),
        sortOrder: 4000,
        completedSortOrder: 1000,
        createdAt: iso(now, 180),
        updatedAt: iso(now, 22),
      },
      {
        id: "demo-task-marketing",
        userId,
        listId: launchId,
        title: "Prepare Vercel domain checklist",
        details: "Env vars, auth redirects, preview URLs, and DNS instructions.",
        color: "coral",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 1000,
        completedSortOrder: null,
        createdAt: iso(now, 80),
        updatedAt: iso(now, 15),
      },
      {
        id: "demo-task-robbins",
        userId,
        listId: launchId,
        title: "robbins seminar",
        details: "",
        color: "violet",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 2000,
        completedSortOrder: null,
        createdAt: iso(now, 72),
        updatedAt: iso(now, 14),
      },
      {
        id: "demo-task-ai-endings",
        userId,
        listId: launchId,
        title: "mit 12 possible endings for AI",
        details: "",
        color: "sun",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 3000,
        completedSortOrder: null,
        createdAt: iso(now, 70),
        updatedAt: iso(now, 13),
      },
      {
        id: "demo-task-gates",
        userId,
        listId: launchId,
        title: "bill gates book",
        details: "",
        color: "mint",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 4000,
        completedSortOrder: null,
        createdAt: iso(now, 68),
        updatedAt: iso(now, 12),
      },
      {
        id: "demo-task-beans",
        userId,
        listId: homeId,
        title: "beans",
        details: "",
        color: "sun",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 1000,
        completedSortOrder: null,
        createdAt: iso(now, 64),
        updatedAt: iso(now, 10),
      },
      {
        id: "demo-task-gmat",
        userId,
        listId: homeId,
        title: "gmat/gre",
        details: "",
        color: "coral",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 2000,
        completedSortOrder: null,
        createdAt: iso(now, 62),
        updatedAt: iso(now, 10),
      },
      ...[
        "https://x.com/heynavtoor/status/206542766611250501773?s=46",
        "https://x.com/viktoroddy/status/2064427319456239351/video/1?s=46",
        "https://x.com/0xchromium/status/2063321324605280569?s=46",
        "https://x.com/raytar/status/2062589304216392059?s=46",
        "https://x.com/sairahul/status/2062807924906411017?s=46",
        "https://x.com/daniel_mac8/status/20599244838789218409?s=46",
        "https://x.com/datachaz/status/20589307356680295064?s=46",
      ].map((title, index) => ({
        id: `demo-task-worklist-${index + 1}`,
        userId,
        listId: worklistId,
        title,
        details: "",
        color: (["sun", "coral", "sky", "mint", "violet", "sun", "coral"] as const)[index],
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: (index + 1) * 1000,
        completedSortOrder: null,
        createdAt: iso(now, 58 - index),
        updatedAt: iso(now, 8),
      })),
      ...[
        "UTD / Classes",
        "UTD / Research",
        "UTD / PA",
        "Career / Internships",
        "Career / Ventures",
        "Career / Brand",
        "Skills / CS",
        "Skills / Finance",
        "Skills / Sales",
        "OS / Sleep",
        "OS / Nutrition",
      ].map((title, index) => ({
        id: `demo-task-plate-${index + 1}`,
        userId,
        listId: plateId,
        title,
        details: "",
        color: (["violet", "violet", "violet", "sky", "sky", "sky", "mint", "mint", "mint", "coral", "coral"] as const)[index],
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: (index + 1) * 1000,
        completedSortOrder: null,
        createdAt: iso(now, 48 - index),
        updatedAt: iso(now, 7),
      })),
      makeTask({
        id: "demo-task-reminders-polyd",
        listId: todayId,
        title: "https://x.com/polydao/status/2062774920770473990?s=46",
        color: "mint",
        sortOrder: 5000,
        minutesAgo: 49,
      }),
      ...Array.from({ length: 7 }, (_, index) =>
        makeTask({
          id: `demo-task-reminders-completed-${index + 1}`,
          listId: todayId,
          title: `completed reminder ${index + 1}`,
          color: "sun",
          isCompleted: true,
          sortOrder: 6000 + index * 1000,
          completedSortOrder: 2000 + index * 1000,
          minutesAgo: 35 - index,
        }),
      ),
      ...MOCKUP_NEXT_TASKS.map((title, index) =>
        makeTask({
          id: `demo-task-next-mockup-${index + 1}`,
          listId: launchId,
          title,
          color: (["sky", "sky", "sky", "sky", "sky", "sky"] as const)[index],
          sortOrder: (index + 5) * 1000,
          minutesAgo: 42 - index,
        }),
      ),
      ...Array.from({ length: 33 }, (_, index) =>
        makeTask({
          id: `demo-task-next-backlog-${index + 1}`,
          listId: launchId,
          title: `saved lead ${index + 1}`,
          color: "sky",
          sortOrder: (index + 11) * 1000,
          minutesAgo: 34 - (index % 20),
        }),
      ),
      ...Array.from({ length: 14 }, (_, index) =>
        makeTask({
          id: `demo-task-bring-completed-${index + 1}`,
          listId: homeId,
          title: `completed bring ${index + 1}`,
          color: "mint",
          isCompleted: true,
          sortOrder: 5000 + index * 1000,
          completedSortOrder: (index + 1) * 1000,
          minutesAgo: 28 - (index % 10),
        }),
      ),
      ...[
        "https://x.com/sukh_saroy/status/2058855918922776962?s=46",
        "https://x.com/elonmusk/status/2059080740881502364?s=46",
      ].map((title, index) =>
        makeTask({
          id: `demo-task-worklist-extra-${index + 1}`,
          listId: worklistId,
          title,
          color: (["coral", "coral"] as const)[index],
          sortOrder: (index + 8) * 1000,
          minutesAgo: 23 - index,
        }),
      ),
      ...Array.from({ length: 141 }, (_, index) =>
        makeTask({
          id: `demo-task-worklist-backlog-${index + 1}`,
          listId: worklistId,
          title: `worklist archive ${index + 1}`,
          color: "coral",
          sortOrder: (index + 10) * 1000,
          minutesAgo: 22 - (index % 20),
        }),
      ),
      ...Array.from({ length: 7 }, (_, index) =>
        makeTask({
          id: `demo-task-worklist-completed-${index + 1}`,
          listId: worklistId,
          title: `completed work item ${index + 1}`,
          color: "coral",
          isCompleted: true,
          sortOrder: 9000 + index * 1000,
          completedSortOrder: (index + 1) * 1000,
          minutesAgo: 25 - index,
        }),
      ),
      ...[
        "Skills / Content",
        "$$$ / Scholarship",
        "$$$ / Budget",
        "OS / Fitness",
        "UTD / Exams",
        "Career / Resume",
        "Career / Network",
      ].map((title, index) =>
        makeTask({
          id: `demo-task-plate-extra-${index + 1}`,
          listId: plateId,
          title,
          color: (["mint", "violet", "violet", "coral", "violet", "sky", "sky"] as const)[index],
          sortOrder: (index + 12) * 1000,
          minutesAgo: 18 - index,
        }),
      ),
      ...Array.from({ length: 5 }, (_, index) =>
        makeTask({
          id: `demo-task-plate-completed-${index + 1}`,
          listId: plateId,
          title: `completed plate ${index + 1}`,
          color: "violet",
          isCompleted: true,
          sortOrder: 22000 + index * 1000,
          completedSortOrder: (index + 1) * 1000,
          minutesAgo: 20 - index,
        }),
      ),
      ...MOCKUP_RAIL_LISTS.flatMap((list, listIndex) =>
        Array.from({ length: list.active }, (_, taskIndex) =>
          makeTask({
            id: `demo-task-${list.slug}-${taskIndex + 1}`,
            listId: `demo-list-${list.slug}`,
            title: `${list.name} ${taskIndex + 1}`,
            color: list.color,
            sortOrder: (taskIndex + 1) * 1000,
            minutesAgo: 20 - (taskIndex % 10) - listIndex,
          }),
        ),
      ),
    ],
    subtasks: [
      {
        id: "demo-subtask-empty",
        userId,
        taskId: inboxTaskId,
        title: "Sort inbox into reminders and Next 3",
        isCompleted: true,
        completedAt: iso(now, 16),
        sortOrder: 1000,
        createdAt: iso(now, 70),
        updatedAt: iso(now, 16),
      },
      {
        id: "demo-subtask-priority",
        userId,
        taskId: inboxTaskId,
        title: "Pull one task to the top",
        isCompleted: false,
        completedAt: null,
        sortOrder: 2000,
        createdAt: iso(now, 65),
        updatedAt: iso(now, 18),
      },
      {
        id: "demo-subtask-sheet",
        userId,
        taskId: polishTaskId,
        title: "Check mobile bottom sheet",
        isCompleted: false,
        completedAt: null,
        sortOrder: 1000,
        createdAt: iso(now, 60),
        updatedAt: iso(now, 18),
      },
    ],
    recurrenceRules: [
      {
        id: "demo-recurrence-daily",
        userId,
        taskId: recurringTaskId,
        frequency: "daily",
        intervalCount: 1,
        daysOfWeek: [],
        monthDay: null,
        startsOn: todayKey,
        endType: "never",
        endDate: null,
        occurrenceCount: null,
        timezone: "America/Chicago",
        paused: false,
        createdAt: iso(now, 80),
        updatedAt: iso(now, 5),
      },
    ],
    preferences: {
      completedOpenByList: {
        [todayId]: false,
      },
      density: "comfortable",
      colorMode: "light",
      boardStyle: "pad",
      taskViewFilter: "all",
      taskSortMode: "custom",
    },
    userState: {
      selectedListId: todayId,
      searchQuery: "",
    },
  };
}
