import { localDateKey } from "@/lib/sticky/recurrence";
import type { StickyWorkspaceData } from "@/types/sticky";

function iso(now: Date, minutesAgo = 0) {
  return new Date(now.getTime() - minutesAgo * 60_000).toISOString();
}

export function createDemoWorkspaceData(): StickyWorkspaceData {
  const now = new Date();
  const todayKey = localDateKey(now);
  const userId = "demo-user";
  const todayId = "demo-list-today";
  const launchId = "demo-list-launch";
  const homeId = "demo-list-home";
  const worklistId = "demo-list-worklist";
  const plateId = "demo-list-plate";
  const inboxTaskId = "demo-task-inbox";
  const polishTaskId = "demo-task-polish";
  const recurringTaskId = "demo-task-recurring";
  const completedTaskId = "demo-task-completed";

  return {
    user: {
      id: userId,
      email: "demo@sticky.local",
      displayName: "AR",
      role: "owner",
    },
    lists: [
      {
        id: todayId,
        userId,
        name: "reminders",
        color: "sun",
        sortOrder: 1000,
        createdAt: iso(now, 360),
        updatedAt: iso(now, 8),
      },
      {
        id: launchId,
        userId,
        name: "Next 3",
        color: "sky",
        sortOrder: 2000,
        createdAt: iso(now, 340),
        updatedAt: iso(now, 12),
      },
      {
        id: homeId,
        userId,
        name: "bring",
        color: "mint",
        sortOrder: 3000,
        createdAt: iso(now, 330),
        updatedAt: iso(now, 30),
      },
      {
        id: worklistId,
        userId,
        name: "Current Worklist",
        color: "coral",
        sortOrder: 4000,
        createdAt: iso(now, 320),
        updatedAt: iso(now, 18),
      },
      {
        id: plateId,
        userId,
        name: "Plate",
        color: "violet",
        sortOrder: 5000,
        createdAt: iso(now, 310),
        updatedAt: iso(now, 22),
      },
    ],
    tasks: [
      {
        id: inboxTaskId,
        userId,
        listId: todayId,
        title: "Clear the capture tray",
        details: "Turn loose ideas into real tasks before lunch.",
        color: "sky",
        dueDate: todayKey,
        dueTime: "11:30",
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 1000,
        completedSortOrder: null,
        createdAt: iso(now, 120),
        updatedAt: iso(now, 12),
      },
      {
        id: polishTaskId,
        userId,
        listId: todayId,
        title: "Tighten the details panel",
        details: "Sharper labels, cleaner due controls, and repeat settings that stay out of the way.",
        color: "violet",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 2000,
        completedSortOrder: null,
        createdAt: iso(now, 100),
        updatedAt: iso(now, 20),
      },
      {
        id: recurringTaskId,
        userId,
        listId: todayId,
        title: "Daily planning pass",
        details: "No subtasks on repeating tasks. Keep it fast.",
        color: "sun",
        dueDate: todayKey,
        dueTime: "09:00",
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 3000,
        completedSortOrder: null,
        createdAt: iso(now, 80),
        updatedAt: iso(now, 5),
      },
      {
        id: completedTaskId,
        userId,
        listId: todayId,
        title: "Sketch first pass motion",
        details: "Completion pulse and drag lift are both wired.",
        color: "mint",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: true,
        completedAt: iso(now, 22),
        sortOrder: 4000,
        completedSortOrder: 1000,
        createdAt: iso(now, 180),
        updatedAt: iso(now, 22),
      },
      {
        id: "demo-task-marketing",
        userId,
        listId: launchId,
        title: "Prepare Vercel domain checklist",
        details: "Env vars, auth redirects, preview URLs, and DNS instructions.",
        color: "coral",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 1000,
        completedSortOrder: null,
        createdAt: iso(now, 80),
        updatedAt: iso(now, 15),
      },
      {
        id: "demo-task-robbins",
        userId,
        listId: launchId,
        title: "robbins seminar",
        details: "",
        color: "violet",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 2000,
        completedSortOrder: null,
        createdAt: iso(now, 72),
        updatedAt: iso(now, 14),
      },
      {
        id: "demo-task-ai-endings",
        userId,
        listId: launchId,
        title: "mit 12 possible endings for AI",
        details: "",
        color: "sun",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 3000,
        completedSortOrder: null,
        createdAt: iso(now, 70),
        updatedAt: iso(now, 13),
      },
      {
        id: "demo-task-gates",
        userId,
        listId: launchId,
        title: "bill gates book",
        details: "",
        color: "mint",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 4000,
        completedSortOrder: null,
        createdAt: iso(now, 68),
        updatedAt: iso(now, 12),
      },
      {
        id: "demo-task-beans",
        userId,
        listId: homeId,
        title: "beans",
        details: "",
        color: "sun",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 1000,
        completedSortOrder: null,
        createdAt: iso(now, 64),
        updatedAt: iso(now, 10),
      },
      {
        id: "demo-task-gmat",
        userId,
        listId: homeId,
        title: "gmat/gre",
        details: "",
        color: "coral",
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: 2000,
        completedSortOrder: null,
        createdAt: iso(now, 62),
        updatedAt: iso(now, 10),
      },
      ...[
        "https://x.com/heynavtoor/status/206542766611250501773?s=46",
        "https://x.com/viktoroddy/status/2064427319456239351/video/1?s=46",
        "https://x.com/0xchromium/status/2063321324605280569?s=46",
        "https://x.com/raytar/status/2062589304216392059?s=46",
        "https://x.com/sairahul/status/2062807924906411017?s=46",
        "https://x.com/daniel_mac8/status/20599244838789218409?s=46",
        "https://x.com/datachaz/status/20589307356680295064?s=46",
      ].map((title, index) => ({
        id: `demo-task-worklist-${index + 1}`,
        userId,
        listId: worklistId,
        title,
        details: "",
        color: (["sun", "coral", "sky", "mint", "violet", "sun", "coral"] as const)[index],
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: (index + 1) * 1000,
        completedSortOrder: null,
        createdAt: iso(now, 58 - index),
        updatedAt: iso(now, 8),
      })),
      ...[
        "UTD / Classes",
        "UTD / Research",
        "UTD / PA",
        "Career / Internships",
        "Career / Ventures",
        "Career / Brand",
        "Skills / CS",
        "Skills / Finance",
        "Skills / Sales",
        "OS / Sleep",
        "OS / Nutrition",
      ].map((title, index) => ({
        id: `demo-task-plate-${index + 1}`,
        userId,
        listId: plateId,
        title,
        details: "",
        color: (["violet", "violet", "violet", "sky", "sky", "sky", "mint", "mint", "mint", "coral", "coral"] as const)[index],
        dueDate: null,
        dueTime: null,
        timezone: "America/Chicago",
        isCompleted: false,
        completedAt: null,
        sortOrder: (index + 1) * 1000,
        completedSortOrder: null,
        createdAt: iso(now, 48 - index),
        updatedAt: iso(now, 7),
      })),
    ],
    subtasks: [
      {
        id: "demo-subtask-empty",
        userId,
        taskId: inboxTaskId,
        title: "Sort inbox into reminders and Next 3",
        isCompleted: true,
        completedAt: iso(now, 16),
        sortOrder: 1000,
        createdAt: iso(now, 70),
        updatedAt: iso(now, 16),
      },
      {
        id: "demo-subtask-priority",
        userId,
        taskId: inboxTaskId,
        title: "Pull one task to the top",
        isCompleted: false,
        completedAt: null,
        sortOrder: 2000,
        createdAt: iso(now, 65),
        updatedAt: iso(now, 18),
      },
      {
        id: "demo-subtask-sheet",
        userId,
        taskId: polishTaskId,
        title: "Check mobile bottom sheet",
        isCompleted: false,
        completedAt: null,
        sortOrder: 1000,
        createdAt: iso(now, 60),
        updatedAt: iso(now, 18),
      },
    ],
    recurrenceRules: [
      {
        id: "demo-recurrence-daily",
        userId,
        taskId: recurringTaskId,
        frequency: "daily",
        intervalCount: 1,
        daysOfWeek: [],
        monthDay: null,
        startsOn: todayKey,
        endType: "never",
        endDate: null,
        occurrenceCount: null,
        timezone: "America/Chicago",
        paused: false,
        createdAt: iso(now, 80),
        updatedAt: iso(now, 5),
      },
    ],
    preferences: {
      completedOpenByList: {
        [todayId]: false,
      },
      density: "comfortable",
      colorMode: "light",
      boardStyle: "pad",
      taskViewFilter: "all",
      taskSortMode: "custom",
    },
    userState: {
      selectedListId: todayId,
      searchQuery: "",
    },
  };
}
