export const POKE_MANUAL_CAPABILITIES = [
  { area: "workspace", action: "read the complete workspace for compound requests", tools: ["get_workspace_snapshot"] },
  { area: "lists", action: "list active and archived lists", tools: ["list_lists"] },
  { area: "lists", action: "create a list", tools: ["create_list"] },
  { area: "lists", action: "rename, recolor, show, or hide a list", tools: ["update_list"] },
  { area: "lists", action: "move or fully reorder lists", tools: ["move_list", "reorder_lists"] },
  { area: "lists", action: "archive and restore a list", tools: ["archive_list", "restore_list"] },
  { area: "lists", action: "permanently delete a list and its contents", tools: ["delete_list"] },
  { area: "tasks", action: "list, search, and inspect tasks", tools: ["list_tasks", "search_tasks", "get_task"] },
  { area: "tasks", action: "create a task with its color, schedule, subtasks, or recurrence", tools: ["create_task"] },
  { area: "tasks", action: "edit title, details, color, due date, due time, and timezone", tools: ["update_task"] },
  { area: "tasks", action: "move a task between lists", tools: ["move_task"] },
  { area: "tasks", action: "move or fully reorder active tasks within a list", tools: ["move_task_in_list", "reorder_tasks"] },
  { area: "tasks", action: "duplicate a task with subtasks or recurrence", tools: ["duplicate_task"] },
  { area: "tasks", action: "complete and restore a task", tools: ["complete_task", "restore_task"] },
  { area: "tasks", action: "permanently delete a task or clear a completed pile", tools: ["delete_task", "clear_completed"] },
  { area: "subtasks", action: "list and inspect subtasks", tools: ["list_subtasks", "get_subtask"] },
  { area: "subtasks", action: "create and independently date a subtask", tools: ["add_subtask"] },
  { area: "subtasks", action: "rename or reschedule a subtask", tools: ["update_subtask"] },
  { area: "subtasks", action: "complete and restore a subtask", tools: ["complete_subtask", "restore_subtask"] },
  { area: "subtasks", action: "move or fully reorder subtasks", tools: ["move_subtask", "reorder_subtasks"] },
  { area: "subtasks", action: "permanently delete a subtask", tools: ["delete_subtask"] },
  { area: "recurrence", action: "list, create, edit, pause, resume, and remove recurrence", tools: ["list_task_recurrences", "create_recurring_task", "make_task_recurring", "set_task_recurrence", "set_task_recurrence_paused", "remove_task_recurrence"] },
  { area: "recurrence", action: "advance overdue recurring tasks", tools: ["advance_recurring_tasks"] },
  { area: "recurrence", action: "undo a recurring completion", tools: ["undo_recurring_completion"] },
  { area: "calendar", action: "list calendars and inspect events", tools: ["list_calendars", "list_calendar_events", "get_calendar_event"] },
  { area: "calendar", action: "create, edit, and permanently delete an event", tools: ["create_calendar_event", "update_calendar_event", "delete_calendar_event"] },
  { area: "calendar", action: "time-block a task", tools: ["time_block_task"] },
  { area: "planning", action: "read a task agenda or combined daily plan", tools: ["get_agenda", "get_daily_plan"] },
  { area: "reminders", action: "list, schedule, and snooze reminders", tools: ["list_reminders", "schedule_reminder", "snooze_reminder"] },
  { area: "daily agenda", action: "preview, change, enable, disable, and test the canonical daily Poke agenda", tools: ["get_daily_agenda_settings", "get_daily_agenda_preview", "update_daily_agenda_settings", "send_daily_agenda_test"] },
  { area: "preferences", action: "read and change persisted workspace view preferences", tools: ["get_workspace_preferences", "update_workspace_preferences"] },
] as const;

export const INTENTIONALLY_HUMAN_ONLY_CONTROLS = [
  "Create, rotate, revoke, or refresh an agent credential.",
  "Connect or disconnect Google OAuth.",
  "Run the owner-only bulk Google-to-Sticky import override.",
  "Grant browser notification permission or register the current device for push.",
  "Sign out of Sticky.",
  "Change device-local navigation and visual state such as the selected task, open panel, search box, rail collapse, calendar viewport, or accent hue.",
] as const;
