-- Poke reminders are explicit per-task choices. Retire pending reminders that
-- were generated by the old automatic ten-minute policy while preserving
-- manual reminders and immutable delivery history.
begin;

update sticky.task_reminders
set status = 'cancelled',
    last_error = null
where status = 'scheduled'
  and is_default = true;

alter table sticky.task_reminders
  drop constraint if exists task_reminders_relative_minutes_check,
  drop constraint if exists sticky_task_reminders_relative_minutes_range;

alter table sticky.task_reminders
  add constraint sticky_task_reminders_relative_minutes_range
    check (relative_minutes is null or relative_minutes between 0 and 525600);

-- Interface sizing is account-persisted. Auto resolves locally from the
-- current viewport, while manual percentage and auto calibration remain
-- stable across reloads.
alter table sticky.user_preferences
  add column if not exists interface_size_mode text not null default 'auto',
  add column if not exists interface_scale integer not null default 100,
  add column if not exists interface_auto_bias integer not null default 0;

alter table sticky.user_preferences
  drop constraint if exists sticky_user_preferences_interface_size_mode_check,
  drop constraint if exists sticky_user_preferences_interface_scale_check,
  drop constraint if exists sticky_user_preferences_interface_auto_bias_check;

alter table sticky.user_preferences
  add constraint sticky_user_preferences_interface_size_mode_check
    check (interface_size_mode in ('auto', 'manual')),
  add constraint sticky_user_preferences_interface_scale_check
    check (interface_scale between 80 and 125),
  add constraint sticky_user_preferences_interface_auto_bias_check
    check (interface_auto_bias between -10 and 10);

notify pgrst, 'reload schema';

commit;
